name: scrna
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - pip
  - pip:
      - scanpy
      - anndata
      - leidenalg
      - python-igraph
      - jupyterlab
      - celltypist
      - shap
      - scikit-learn
      - matplotlib
      - seaborn
      - pandas
      - numpy
